server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PrasadHonrao/spring-petclinic-microservices-config
          default-label: main
          username: PrasadHonrao
          password: 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
        # Use the File System Backend to avoid git pulling. Enable "native" profile in the Config Server.
        native:
          searchLocations: file:///${GIT_REPO}

